### PR TITLE
Fix npm 2.x build failures for angular-material-source dependency

### LINKED ISSUE #349: Latest master branch does not build
Installing the latest master branch fails to build.

`npm --version`  

> 2.147

`ember --version`

> ember-cli: 2.4.3
node: 4.2.3
os: darwin x64

Here are the steps I took to reproduce:

- npm cache clean
- bower cache clean
- ember new eptest
- cd eptest
- ember install https://github.com/miguelcobain/ember-paper.git#master

> Installed packages for tooling via npm.
installing ember-paper
  create app/styles/app.scss
  install bower packages hammer.js, matchMedia
  not-cached https://github.com/hammerjs/hammer.js.git#*
  not-cached https://github.com/paulirish/matchMedia.js.git#0.2.0
  resolved https://github.com/paulirish/matchMedia.js.git#0.2.0
  resolved https://github.com/hammerjs/hammer.js.git#2.0.8
Installed browser packages via Bower.
  install package ember-cli-sass
⠙ Installing packages for tooling via npmBinary downloaded and installed at /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-46/binding.node
⠸ Installing packages for tooling via npm"/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists.
 testing binary.
Binary is fine; exiting.
Installed packages for tooling via npm.
Installed addon package.

- ember build

> Build failed.
The Broccoli Plugin: [Funnel: AngularScssFunnel] failed with:
Error: ENOENT: no such file or directory, lstat '/Users/daniel.monroe/projects/training/ember/eptest/node_modules/angular-material-source/src'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:60:26)
    at symlinkOrCopySync (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:55:5)
    at /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)
The broccoli plugin was instantiated at:
    at Funnel.Plugin (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/index.js:44:10)
    at Class.module.exports.treeForStyles (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/index.js:112:28)
    at Class._treeFor (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:461:30)
    at EmberApp.styles (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:1243:25)
    at EmberApp.toArray (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:1565:10)

package.json:

> {
  "name": "eptest",
  "version": "0.0.0",
  "description": "Small description for eptest goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.4.3",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.2",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-paper": "git+https://github.com/miguelcobain/ember-paper.git#1ec9596ece800afe76ad490f4f53f260b9b779e6",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.1"
  }
}

bower.json:

> {
  "name": "eptest",
  "dependencies": {
    "ember": "~2.4.3",
    "ember-cli-shims": "0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "hammer.js": "^2.0.8",
    "matchMedia": "0.2.0"
  }
}

### PR DESCRIPTION
**Pull request by eriktrom**
- Angular-material-source does not have a main node module, its only
  built to ./dist and published via bower. The first attempt to make
  this work with npm 3.x broke (some users) npm 2.x env's.

- This aims to allow building a project that includes this addon for
  npme 2.x and 3.x for all versions of node.

fixes #349

### CODE REVIEW

**Comment by eriktrom** [comment]
Note the difference is the use of `this.nodeModulesPath` instead of `this.project.nodeModulesPath`

`this.nodeModulesPath` is defined in both addon.js and project.js

Addon: https://github.com/ember-cli/ember-cli/blob/feddfd099156b8aa13d21ee2ee903fa0c86e2408/lib/models/addon.js#L102

Project: https://github.com/ember-cli/ember-cli/blob/feddfd099156b8aa13d21ee2ee903fa0c86e2408/lib/models/project.js#L108

(crosses fingers)

@cah-danmonroe @thijsvdanker - do either of you mind giving this a whirl, thanks a bunch

**Comment by DanChadwick** [comment]
I checkout this commit and deleted angular-material-source from ember-paper/node_modules and my-project/node-modules. In ember-paper, I `npm link`ed and it reinstalled angular-material-source. In my project, I `npm install`ed and it did the same. It then built correctly. npm v2.14.7. I can't say for sure whether this worked before, but it certainly worked now. Windows, for what it's worth.

**Comment by eriktrom** [comment]
@DanChadwick - your awesome - once @cah-danmonroe or @thijsvdanker can verify it works for them, i think we can merge. 

I never had an issue w/ 2.x and node 0.12 (and neither does travis). :shrugs:

**Comment by cah-danmonroe** [comment]
This commit didn't work for me either.
node v4.2.3, npm 2.14.7
on a mac

> /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules   master ✘ ✹ ✭
 ll                                                                                                                                                             
total 0
drwxr-xr-x   9 daniel.monroe  CARDINALHEALTH\Domain Users  306 May  4 18:36 .
drwxr-xr-x  18 daniel.monroe  CARDINALHEALTH\Domain Users  612 May  4 18:36 ..
drwxr-xr-x  24 daniel.monroe  CARDINALHEALTH\Domain Users  816 May  4 18:36 angular-material-source
drwxr-xr-x   7 daniel.monroe  CARDINALHEALTH\Domain Users  238 May  4 18:36 broccoli-autoprefixer
drwxr-xr-x   9 daniel.monroe  CARDINALHEALTH\Domain Users  306 May  4 18:36 broccoli-filter
drwxr-xr-x  14 daniel.monroe  CARDINALHEALTH\Domain Users  476 May  4 18:36 broccoli-funnel
drwxr-xr-x  18 daniel.monroe  CARDINALHEALTH\Domain Users  612 May  4 18:36 broccoli-merge-trees
drwxr-xr-x  12 daniel.monroe  CARDINALHEALTH\Domain Users  408 May  4 18:36 ember-css-transitions
drwxr-xr-x  14 daniel.monroe  CARDINALHEALTH\Domain Users  476 May  4 18:36 ember-wormhole

Here's my package.json:

> {
  "name": "eptest",
  "version": "0.0.0",
  "description": "Small description for eptest goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.4.3",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.2",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-paper": "git+https://github.com/miguelcobain/ember-paper.git#6f95be81ea20eca54d1c6ee70eb30ef86372f3e5",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.1"
  }
}

**Comment by cah-danmonroe** [comment]
ember-paper>  git pull origin pull/364/head
npm link

eptest>  rm -rf node_modules
eptest>  npm link ember-paper
eptest>  npm install
eptest>  ember build
Built project successfully. Stored in "dist/".

Didn't try an ember build before linking.  Going to unlink and test that now.

**Comment by cah-danmonroe** [comment]
unlinked, it builds (and runs) as well.  However, it is still putting all the ember-paper dependancies under the node_modules/ember-paper/node_modules directory.

(thumbs_up)

File: index.js [hunk 1]
```diff
@@ -106,10 +106,19 @@ module.exports = {
...
+    /*
+      Find the angular-material-source module in a manner that works for npm 2.x
+      and 3.x in both the addon itself and projects that depend on this addon
+
+      This is an edge case b/c angular-material-source does not have a main
+      module we can require.resolve through node itself and similarily ember-cli
+      does not have such a hack for the same reason.
+
+      tl;dr - We want the non built scss files, and b/c this dep is only provided via
+      bower, we use this hack. Please change it if you read this and know a better way.
```
Comment (miguelcobain) [inline index.js]: > this dep is only provided via bower

Why do you say that? We're not using bower for the `angular-material-source` dependency.

**Comment by miguelcobain** [comment]
```bash
$ ember new paper-test
$ cd paper-test
$ ember install eriktrom/ember-paper#fix-npm-2.x-build-error
$ ember s
```
This worked, so I assume it is fixed.
Thanks.

**Comment by miguelcobain** [comment]
@eriktrom Please explain the reasoning behind your comment so we can update accordingly.

File: index.js (hunk 1 above)
Comment (eriktrom) [inline index.js]: They build to their dist directory and publish that to bower only. Their package.json has no main property and the project has no index.js file so tl;dr - there is no way to require their library from another node module - which after looking at some other addons like liquid fire and the node docs, would be our first choice for finding the path for all npm + node versions cleanly via 'path.dirname(require.resolve("angular-material-source"))/src' 

This is like the rest of the angular microlibs - they chose to use bower only for deps that used by angular 

We could file a ticket to add an empty index.js file in their repo but not sure they'd go for it. 

Check the node docs for the 'module' module towards the bottom and then try to find any of the termination steps that will resolve module.main in their code base and you'll see what I mean. I found none

And correct were not using bower, we want the actual source scss, but we're having to hack our own way to find it, which is just weird for sure - although currently ember uses the same pattern (until it becomes addon)

(on my phone ATM so let me know if that made sense - wow using mobile is hard on github, can't even see what I just wrote)

Comment (miguelcobain) [inline index.js]: Ah, I see now.
If `this.nodeModulesPath` points to whatever the current dir for node modules is, then I guess we'll always be fine. Is this correct?

Comment (eriktrom) [inline index.js]: Yeah if that comment in the code base is confusing I should change it.  Wanted to explain it is a hack in as few words as possible but to really explain it is rather in depth. If ur brain comes up with a one line comment let's use it  👌

Comment (eriktrom) [inline index.js]: Yeah that is the logic.

Comment (eriktrom) [inline index.js]: Only odd thing is people had bugs with this.project.nodeModulesPath - when they were in their project.  So I'd love verification from those users.

Comment (miguelcobain) [inline index.js]: I see the reasoning. But I don't see this exactly as a "hack". In the sense that "I don't see how this can ever go wrong".

Comment (eriktrom) [inline index.js]: Just spun my brain. this.nodeModulesPath does make sense. (For exactly ur comments reason). Whoo!

**Comment by miguelcobain** [comment]
Can someone with npm3 run the steps illustrated above and confirm it works?

File: index.js (hunk 1 above)
Comment (eriktrom) [inline index.js]: I don't think it'll go wrong.  It's a hack b/c if it were s real node module we could just require it. But it has no export, so they use it just to install deps, not to be installed by others itself.

Comment (eriktrom) [inline index.js]: As a last comment there - if it were installed globally we'd have no clue where to look but node would

Comment (eriktrom) [inline index.js]: Good grief - that's a lie too. It shakes out fine in all cases. Sorry I was up all nite. I think it's good to merge.

Comment (eriktrom) [inline index.js]: Before I sign off for a bit should we leave the comment so we don't forget or remove it?

Comment (miguelcobain) [inline index.js]: I'd prefer a slight rewording. The way it is written looks like it is a hack from ember-paper. It's not really our fault. Besides that, the solution is better than what the comments make it sound.

**Comment by jtferns** [comment]
👋 wanted to mention that I was running into issues when getting a new app with the latest `ember-paper` built (node 6.1.0, npm 3.8.6) in Circle CI due to the `angular-material-source` not being found during the addon tree building step; my local workaround was to add `"angular-material-source": "angular/material#v1.0.5"` (basically an unused dependency) to prevent NPM from moving the `1.0.6` dependency to my project's `node_modules`

repro steps were the following:
- create ember app
- install ember-paper: `ember install miguelcobain/ember-paper`
- clear node_modules: `rm -rf node_modules/`
- install fresh node modules:  `npm install`
- attempt a build: `ember build`

```bash
The Broccoli Plugin: [Funnel: AngularScssFunnel] failed with:
Error: Attempting to watch missing directory: <EMBER-APP-ROOT>/node_modules/ember-paper/node_modules/angular-material-source/src
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (<EMBER-APP-ROOT>/node_modules/broccoli-sane-watcher/index.js:90:11)
    at <EMBER-APP-ROOT>/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (<EMBER-APP-ROOT>/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (<EMBER-APP-ROOT>/node_modules/rsvp/dist/rsvp.js:505:17)
    at <EMBER-APP-ROOT>/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (<EMBER-APP-ROOT>/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (<EMBER-APP-ROOT>/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (<EMBER-APP-ROOT>/node_modules/broccoli-funnel/index.js:44:10)
    at Class.module.exports.treeForStyles (<EMBER-APP-ROOT>/node_modules/ember-paper/index.js:121:28)
    at Class._treeFor (<EMBER-APP-ROOT>/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (<EMBER-APP-ROOT>/node_modules/ember-cli/lib/models/addon.js:290:19)
    at <EMBER-APP-ROOT>/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
    at Array.map (native)
    at EmberApp.addonTreesFor (<EMBER-APP-ROOT>/node_modules/ember-cli/lib/broccoli/ember-app.js:461:30)
    at EmberApp.styles (<EMBER-APP-ROOT>/node_modules/ember-cli/lib/broccoli/ember-app.js:1243:25)
    at EmberApp.toArray (<EMBER-APP-ROOT>/node_modules/ember-cli/lib/broccoli/ember-app.js:1565:10)
```

**Comment by eriktrom** [comment]
Thanks @jtferns. I think I see a way forward here - I'm a bit wrapped up ATM and don't have the issue u mention, although after upgrading to node 6 I reverted back to 5 in a number of repos due to module resolution errors, many of which seem similar to what u mention (at least in nature). 

I do believe I got this to work once (before I decided I had things to do instead of upgrade again ATM) - but I recall getting it all working did not come without pain so I'll fix it up soon

Btw - what version of ember-cli, in case that matters when I debug. Thanks.

**Comment by eriktrom** [comment]
Also is this only for circle CI? That would shed light as well.  Does this work on ur local machine?

**Comment by jtferns** [comment]
@eriktrom no worries, glad to shed💡 here; I've had this issue in Circle CI _and_ locally (the repro steps above were local and identical to the errors I was getting on Circle CI);

My `ember -v` output is:
```bash
ember-cli: 2.5.1
node: 6.1.0
os: darwin x64
```

**Comment by eriktrom** [comment]
Gratzi.  The problem in that stack trace btw is b/c isDevelopingAddon is true - which makes ur app watch the addons own deps, for live reload when npm linking, something you don't want for a --prod build obviously.  (I'll dig deeper later, but that's the gist of it for the curious - And note to self for later :P)

**Comment by jtferns** [comment]
ah, I see; I've had that flag enabled for in-repo addons but not for external ones, good to know! thanks for 🔍 -ing into this 😄

**Comment by bdmac** [comment]
@miguelcobain this fix does not work for us on node v5.1.0. Get the same error @jtferns mentioned above. This happens both to other developers that did NOT run `ember install ember-paper` (just ran npm install) and when we deploy.

**Comment by eriktrom** [comment]
@bmac - what version of npm? 

Also where in your node modules tree is angular-material-source located - I actually have the same problem now after I re-installed all my modules recently - I'd like to fix it (and npm with ember in general at some point - I've resorted to checking my modules in!)

any info helps, thanks

**Comment by eriktrom** [comment]
For reference - I'm obviously not sure what the real issue is - but what i said earlier in this thread is irrelevant or wrong - it has to do with **where npm puts your modules** and the fact that `require.resolve('angular-material-source')` does not return the main module, b/c its not listed under the main property in their package.json - leaving the resolution path to the directory we need difficult to be determinate about... 

If we we're to make angular-material-source into an ember-cli addon, this would go away - in the meantime, a way to fix it for sure is to copy angular-material-source from node_modules (its likely in the root of node_modules) into /node_modules/ember-paper/node_modules/angular-material-source - for your deploy script, make sure its there before you run ember deploy - this is the only sure fire way without making a module as npm makes duplicated copies of the modules it installs without running npm dedupe && npm prune, at which point angular-material-source will end up in the root of node_modules anyway (you can see this in action by running npm-shrinkwrap --dev and reading all the duplicate packages in node_modules, its a nightmare ATM IMO)

**Comment by eriktrom** [comment]
One more note, my knowledge of this problem is mostly informed by this doc (npm module resolution algo, worth the read for those interested in helping discuss a solution to this):

https://nodejs.org/api/modules.html#modules_all_together
